[MINOR] Eliminate the usage of the shaded Guava Sets class (#2432)
### What changes were proposed in this pull request?

Replacing shaded guava's `Sets` class usage with `HashSet`

### Why are the changes needed?

Hadoop can throw this error if the classpath is not correctly set:
```
org.apache.uniffle.client.impl.ShuffleWriteClientImpl: Unexpected exceptions occurred while sending shuffle data
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/apache/hbase/thirdparty/org/glassfish/jersey/internal/guava/Sets
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

UTs.