[#2563] improvement(spark): Add more logs of shuffle write on reassignment failure (#2564)
### What changes were proposed in this pull request?

This PR is to add more logs of shuffle write on reassignment failure for the next inspection when it occurs.

### Why are the changes needed?

for #2563 .

```
25/07/29 08:13:25 ERROR TaskResources: Task 14257 failed by error: 
org.apache.uniffle.common.exception.RssException: No available replacement server for: 10.xxxxx-23100-23104
	at org.apache.spark.shuffle.writer.RssShuffleWriter.reassignAndResendBlocks(RssShuffleWriter.java:832)
	at org.apache.spark.shuffle.writer.RssShuffleWriter.collectFailedBlocksToResend(RssShuffleWriter.java:672)
	at org.apache.spark.shuffle.writer.RssShuffleWriter.checkDataIfAnyFailure(RssShuffleWriter.java:570)
	at org.apache.spark.shuffle.writer.RssShuffleWriter.checkBlockSendResult(RssShuffleWriter.java:532)
	at org.apache.spark.shuffle.writer.RssShuffleWriter.internalCheckBlockSendResult(RssShuffleWriter.java:518)
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Neen't